filebeat.inputs:
  - type: log
    enabled: true
    fields:
      index_type: access-log
      project_name: ${PROJECT_NAME}
    fields_under_root: true
    paths:
      - "/var/log/nginx/access.log"
  - type: log
    enabled: true
    fields:
      index_type: error-log
      project_name: ${PROJECT_NAME}
    fields_under_root: true
    paths:
      - "/var/log/nginx/error.log"
  - type: log
    enabled: true
    fields:
      index_type: spring-log
      project_name: ${PROJECT_NAME}
    fields_under_root: true
    paths:
      - "/var/log/spring/spring.log"
    multiline.pattern: "^([0-9]{4}-[0-9]{2}-[0-9]{2})"
    multiline.negate: true
    multiline.match: after
    multiline.skip_newline: true

output.logstash:
  hosts: ["${LOGSTASH_URL}"]
  ttl: 1m
